apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: install
spec:
  inputs:
    resources:
      - name: hello-react-app
        type: git
  steps:
    - name: npm-install
      image: node:14
      command:
        - /bin/sh
        - -c
      workingDir: /workspace/hello-react-app/
      args:
        - npm install
