apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: lint
spec:
  inputs:
    resources:
      - name: hello-react-app
        type: git
  steps:
    - name: lint
      image: node:14
      command:
        - /bin/sh
        - -c
      args:
        - npm run lint
      workingDir: /workspace/hello-react-app
