apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-pipeline-run
spec:
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tkn-pvc
      subPath: ""
  pipelineRef:
    name: nodejs-pipeline
