apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read
spec:
  workspaces:
    - name: output
  steps:
    - name: read
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ["-c", "ls $(workspaces.output.path)/app"]
